name: communiapp
description: Super App local con CAMI powered by Grok
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  flutter_riverpod: ^2.5.1
  hydrated_riverpod: ^2.5.1
  path_provider: ^2.1.4
  geolocator: ^13.0.1
  geoflutterfire2: ^2.3.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
